### PR TITLE
Automatically map controls for SteelSeries Stratus and Gamesir M2 MFI controllers

### PR DESCRIPTION
**Pull request by inekipelov**

### CODE REVIEW

**Comment by clobber** [comment]
Questions:

1. Have you confirmed these to work and to be correct?
2. Which SteelSeries Stratus device exactly?  Is it [this one](https://www.amazon.com/gp/product/B00IODWU6W)? There is conflicting information online that the VID/PID is actually the XL version.

**Comment by inekipelov** [comment]
@clobber 
> 1. Have you confirmed these to work and to be correct?
Sure. I have both gamepads. And I can check how it works

> 2. Which SteelSeries Stratus device exactly?  Is it [this one](https://www.amazon.com/gp/product/B00IODWU6W)? There is conflicting information online that the VID/PID is actually the XL version.
Thanks. After your comment, I did found it also

I close this pull request and will make a new one later

**Comment by clobber** [comment]
There was no need to close. I just wanted confirmation of these work and you tested them.

**Comment by clobber** [comment]
@inekipelov Can you confirm that both of these work to automap controls for those devices, both SteelSeries Stratus and Gamesir M2 MFI controllers? That's all I need to know.

**Comment by inekipelov** [comment]
@clobber SteelSeries Stratus conflicts with plist for XL version. #4427 contains changes only for GameSir M2, and it works fine

**Comment by clobber** [comment]
> SteelSeries Stratus data conflicts with plist for XL version

How can they conflict? They have entirely **different** Product IDs.

Your pull request:

https://github.com/OpenEmu/OpenEmu/pull/4422/files#diff-750a717d6c835e322a131f7625c7281a54a0c3fc267e2856452d261f6ef5ed56R3078

> 5145

versus our database:

https://github.com/OpenEmu/OpenEmu/blob/aea4c54eef06d63fcf740365113bf3ed6a969ae7/OpenEmu/Controller-Database.plist#L3070

I will ask you **one last time**: did you test to confirm it works or not?

**Comment by inekipelov** [comment]
I cannot confirm work Steelseries Stratus controller right now. But can absolutely confirm Gamesir M2. That's why I create #4427

**Pull request closed without merging**
