### PR TITLE
Add Mayflash GameCube controller to the DB and associated mappings

### PR DESCRIPTION
**Pull request by lexi-lambda**

### CODE REVIEW

**Comment by Streusel** [comment]
@cyco back to your question.

**Comment by clobber** [comment]
Yes. Very hesitant to merge in support for adapters and generic gamepad clone devices because as we learned with the Retrolink and RetroUSB devices, these vendor and product ID's are often shared by other generic USB adapters causing us a world of pain.

**Comment by frankymacster** [comment]
How do I add this piece of code into OpenEmu?

**Comment by ngude** [comment]
any possibility in this happening? this same issue occurs even with the genuine nintendo gamecube adapter.

**Comment by ddbehsnilian** [comment]
Any hopes for the original Wii U adapter? I ask because I have used it directly with Dolphin Emu and it works flawlessly.

**Comment by braco** [comment]
Seems like this issue still exists? Used OpenEmu for the first time and can't get GC controller to map properly.

**Comment by dschuessler** [comment]
Maybe the user can be prompted to verify that its actually the controller in question that he plugged in. If there is more than one controller sharing the vendor/product id, he could choose from a list.

**Pull request closed without merging**
