### PR TITLE
Update Cheats Setting

### PR DESCRIPTION
**Pull request by kagenZhao**
1, Add new window for cheats setting(Localization supported).
2, Use CoreData to save cheats
image

### CODE REVIEW

**Comment by SuperTurn** [comment]
I would love to see this feature added. Can we get an ETA?

**Comment by Coaggly** [comment]
Any word on this being implemented?

**Comment by kagenZhao** [comment]
@Coaggly  I don’t know, it’s been a year since this pull request

**Comment by AstroOrbis** [comment]
bump i guess?

**Comment by clobber** [comment]
Besides the fact that OE's codebase has changed dramatically and this obviously cannot be merged due to conflicts, there are other problems:

1. There is no explanation as to what your patch does.
2. It should be written with modern macOS development in mind, using Swift and possibly SwiftUI and not Obj-C with NIBs. Programmatically at the very least.

**Pull request closed without merging**
