### PR TITLE
Fix a Crash in Preferences > Controls on N64

### PR DESCRIPTION
**Pull request by RobertMenke**
## Description

Fixes an issue that causes a crash on OpenEmu 2.1.1 while navigating to Preferences > Controls for N64. The error is caused by a call to `OEPopUpButtonCell`'s `attributedTitle` method returning an empty `NSAttributedString`. The resulting exception message is `Crashing on exception: NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds`

Initially reported on [Reddit](https://www.reddit.com/r/OpenEmu/comments/dqmycf/openemu_211_released/f6ife0k)

### CODE REVIEW

**Comment by robotoad** [comment]
This looks like a sensible change, but before merging, I wanted to ask if there's a set of steps to replicate the crash since we haven't been able to ourselves, just to make sure there's not some other issue at play.

**Comment by robotoad** [comment]
Also, which particular pop-up button is displaying an empty title?

**Comment by RobertMenke** [comment]
@robotoad I can send a screenshot of the N64 Preferences > Controls screen tomorrow when I'm at my personal computer that may be helpful. The only thing I can think of is that I used to play N64 via OpenEmu with a PS4 controller on Mojave. The crash started happening when I upgraded to Catalina. I know that Apple has made quite a few changes to their handling of game controllers.

**Comment by robotoad** [comment]
After your code change, is the "Input:" pop up button displaying as empty for you?

**Comment by RobertMenke** [comment]
I'll let you know tomorrow morning. I'm on my work machine now and am hosting a meetup tonight so I won't have any time to get you the info you need today. Thanks for your time and I'll send over that info tomorrow!

**Comment by robotoad** [comment]
Thanks. We suspect deleting your bindings file may fix the issue, but we'd like more information on  the cause of the bug, so it would be useful if you could upload a copy of that file for us.

You can find it by navigating to `~/Library/Application Support/OpenEmu/Bindings` (where `~` is your username. See here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/). There should be a file named `Default.oebindings`.

**Comment by cyorobert** [comment]
Great! I'll try that and report back. Thanks!

**Comment by robotoad** [comment]
In the meantime, we've decided not to merge this because we think it masks a greater issue, and we don't want an empty title in the pop-up button. You can still report back here when you have access to your personal computer tomorrow.

**Comment by RobertMenke** [comment]
N64_Prefs_Controls

[Default.oebindings.zip](https://github.com/OpenEmu/OpenEmu/files/3826882/Default.oebindings.zip)

Hey @robotoad I've uploaded a screenshot of the N64 controls menu that I see after adding the check to see if the title is empty. I also uploaded my Default.oebindings file. I tried deleting the file to see if it resolved the issue but I'm still experiencing the same crash. I tried downloading 2.1.1 over again from the website, but I get the same crash and the Default.oebindings file was not regenerated.

Sorry for being a pain! I sent your org $50 for the support. Thanks again!

**Comment by robotoad** [comment]
This screenshot raises some eyebrows! It's not the Input pop-up button that's empty like we suspected but the system list. Even stranger, icons are missing for the different preference panes.

So, some questions: Is this a custom build of OpenEmu or any of its components? Have you manually modified OpenEmu's `Application Support` files in any way beyond what you've been instructed to do here?

Our suggestion now is to close OpenEmu, delete the contents of `~/Library/Application Support/OpenEmu/Cores/` as well as `~/Library/Application Support/OpenEmu/System/` if that folder exists, and relaunch OpenEmu.

As a last resort, you can nuke the entire `~/Library/Application Support/OpenEmu/` folder and start over with a fresh installation. Note that this will delete your library of screenshots, save states, and imported ROMs, so if you have anything important, you'll want to back up those files to be re-imported afterward.

**Comment by RobertMenke** [comment]
Hello again @robotoad, deleting the entire `~/Library/Application Support/OpenEmu/` folder did the trick for me (tried the other methods first with no luck). I downloaded the Catalina beta mid-summer to explore the new SwiftUI and Combine frameworks and it was an extremely buggy beta. Definitely appears to be an error on my part testing out Apple's unstable software prior to OpenEmu having a chance to get ready for Catalina. 

Thank you very much for your support and thanks to the entire OpenEmu team for working hard on such an incredible open-source project! I've had countless hours of joy playing games I loved during my childhood because of your hard work.

I'll post the exact steps I took here in case anyone else stumbles upon this issue.

1) Back up OpenEmu files to your desktop (via terminal/iterm2/hyper/etc)
```bash
cp -r ~/Library/Application\ Support/OpenEmu ~/Desktop/OpenEmu
```

2) Remove the existing OpenEmu files (via terminal/iterm2/hyper/etc)
```bash
rm -rf ~/Library/Application\ Support/OpenEmu
```

3) Move OpenEmu.app to trash. Go to finder > Application > OpenEmu, drag it to your trash, and empty the trash.

4) Redownload OpenEmu from the website https://openemu.org/

5) Open up the application and drag your games into the appropriate emulators.

I didn't have any save states or screenshots I really cared about, but if you do they all exist in that folder we copied to the Desktop in step 1. If you'd like to preserve them, carefully select the appropriate items and move them back to `~/Library/Application\ Support/OpenEmu`.

**Pull request closed without merging**
