### PR TITLE
Update all localizations.

### PR DESCRIPTION
**Pull request by shysaur**
Now that the UI overhaul seems to have mostly ended, I thought this is probably the right time to update all the localized xibs. All the available translations now work correctly, including the Russian one which has been excluded from building since forever.

Sadly, this doesn't make all the translations ready to ship with the next version; for example, Spanish has some text overflow issues and the new Library toolbar is untranslated everywhere. I am opening this pull request anyway because merging the xibs will only become more difficult over time. 

For each translation I have done some functional tests by opening a freshly compiled OpenEmu and using it for a while, and then I compared all the xibs with the English equivalents using FileMerge. I had no problems using any of the translated versions, and the only differences I saw in FileMerge between the English xibs and the localized xibs were the translated strings and some labels and buttons changing size and placement to accomodate the new text. I fixed some OEButton height changes which caused incorrect drawing.

To preserve my sanity while updating the xibs, I made a [little shell script](https://gist.github.com/shysaur/b3de0ac2110e524a73bb) that looks for outdated localized xibs and automatically runs ibtool on them to bring them up to date with the xibs in the base language. Run the script before or after committing, giving the path to OpenEmu/en.lproj as the only argument, and it will bring every localized xib up to date automatically. Note that it won't work correctly after a rebase, and it has issues with renames (both these limitations can be worked around).

### CODE REVIEW

**Comment by cyco** [comment]
Looks pretty good. Thanks for your help.

**Comment by clobber** [comment]
@shysaur, thanks. Just for clarification, with your method for updating these can we rule out any issues between the primary english xibs and the localized ones? I was planning to delete all the localized xibs and then manually recreate them based off the english, then readd all the localized strings. I just want to make sure a user with a localized version doesn't run into weird bugs or crashes, which we once had before. All the code in the xibs should match the english with the exception of some strings and sizing adjustments.

**Comment by shysaur** [comment]
If the translator mistakenly introduced any bug, the bugs will carry over, but if there are no translation-dependent bugs to begin with, my tool will not introduce them.

**Comment by clobber** [comment]
Okay, @cyco we need to revert this or wipe the xibs then. There were definitely issues in the localized xibs.

**Comment by shysaur** [comment]
I'm pretty sure there are no problems now, I manually compared all the xibs after updating them, and there were no changes that could have caused problems. You can compare them yourself if you want, just use FileMerge (disable the xib filter in the preferences first, it's pretty useless).

Probably, the problems you had were caused by changing the English xibs without updating the localized xibs with the changes.

**Pull request merged**
