### PR TITLE
Localization, Auto Layout, etc.

### PR DESCRIPTION
**Pull request by J-rg**
Updated OEPrefLibraryController and OEPrefGameplayController to Auto Layout

http://cl.ly/0J1z2C2T0W1T
http://cl.ly/3t1X431H1z3a

I made sure everything looks the same, however, there are two issues I wasn’t able to fix.

* The list of available systems is now pinned to the bottom and unscrollable. After (de)selecting a system, the list becomes scrollable again.

* There is no padding on the left and right side of a button when it adapts to longer texts.
This could be fixed by creating a hidden button with the same text and link them with an Equal Width +10px constraint, but I’m sure there’s a more elegant solution.

### CODE REVIEW

**Comment by cyco** [comment]
I'll merge this in, but i'm not sure about the game scanner shadows or the space between toolbar and background color view. Those could be intentional. We'll just have to see how it looks.

**Comment by cyco** [comment]
Thanks for the help btw :)

**Comment by cyco** [comment]
Animation for the gameplay preferences is glitching now. Do you have time to fix that?

**Comment by robotoad** [comment]
Autolayout is complaining in the console about conflicting constraints.

**Comment by clobber** [comment]
The scroll view in the bottom inset under "Library" preferences doesn't scroll for me.

**Comment by clobber** [comment]
And this just happened changing tabs...
screen shot 2015-12-22 at 10 44 11 am

**Comment by clobber** [comment]
Sorry, I reverted this for now. We don't have time to thoroughly test to find all the problems because we're trying to get a new release out.

**Comment by shysaur** [comment]
I was looking at this today, and I could fix the scroll view. Then I tried to fix the glitch resizing, and I was just writing here to say I couldn't fix it when I got an eureka! moment and I managed to find a fix for that too!

If you want, I can make a pull request with the fixes, but you are trying to get a release done after all, and I don't want to interfere with that. Anyway, I wrote a not-really-short explanation of the resizing glitch below.

During the animation the panel view updates its layout, and this was no problem before the autolayout change, because there were no autoresizing masks that could cause the controls' sizes to change.

But, @J-rg added some constraints that tied the right side of most controls to the right side of their parent view (and, by extension, the enclosing window). When the animation starts, the autolayout engine tries to fit the controls into the frame, and it sees they must all hug the sides of the window, which is larger than the final size. On the gameplay panel, there is a single separator which has no height set. So, the autolayout engine makes all the other views hug the window borders, and then it expands the separator so that it hugs the controls above and below it as specified by the constraints.

Since that separator is an NSView subclass with no intrinsic sizing requirement, at the end of the process the autolayout engine sets the view's fittingSize to this wrong size that's too big. Since autolayout knows and looks at fittingSize, and it treats it as an additional constraint, that view stays too big during the entire duration of the animation, causing the glitch.

But, if we remove all the constraints that tie each subview to the right border of the preference panel view (adding some constraints to specify the size of the controls that don't have one), each subview can stay at the right size whatever the size of the window is, and the glitch is fixed.

(I tried to just add a height constraint to the offending separator, but it did not work because it caused other similar glitches when switching to the other panels; for example, the Library prefpane's scroll view would collapse to a thin line)

**Pull request merged**
