### PR TITLE
Update spanish localization

### PR DESCRIPTION
**Pull request by pulsedrivervstibby**
Update spanish localization and delete strings unused in all localizable.strings.

### CODE REVIEW

**Comment by clobber** [comment]
@pulsedrivervstibby I'm not so sure all of those strings you have deleted are "unused."

For now, can you just stick to doing a pull request that updated that Spanish localization?

**Comment by pulsedrivervstibby** [comment]
Ok, only update the spanish localization.

Can you help me to rollback all commits?

**Comment by clobber** [comment]
There's no easy way for me to walk you through this without having to use `git` from the command line.

So, for the sake of time and ease, just fork the OpenEmu repo again and create a branch with only your Spanish language changes and then submit that as a Pull Request - and please try to keep everything down to a single commit.

Look into using the [GitHub Desktop app](https://desktop.github.com/) where you can make changes to multiple files as a single commit. That will help to keep your commits looking cleaner.

**Comment by pulsedrivervstibby** [comment]
Hallo i create a new pull request with a spanish localization.  I close this one.

**Pull request closed without merging**
