### PR TITLE
Update Italian localization.

### PR DESCRIPTION
**Pull request by shysaur**
I also added the "Send a Donation..." menu item string to all localizations, since it was missing.

### CODE REVIEW

**Comment by clobber** [comment]
Thanks. One issue though, it looks like the other locales have it translated to "Send a Donation???" instead of "Send a Donation…" with the ellipsis.

**Comment by clobber** [comment]
Oh, maybe that is a encoding problem on GitHub?

Anyway, one other thing: the MainMenu.strings for the Japanese locale should already have that string. Looks like the only one that already did have it.

https://github.com/OpenEmu/OpenEmu/blob/master/OpenEmu/ja.lproj/MainMenu.strings#L266-L267

**Comment by shysaur** [comment]
Fixed the issue with Japanese.

And yeah, those question marks are indeed caused by Github's encoding detection heuristic failing if there is not enough text displayed (viewing the entire file fixes the issue).

**Comment by clobber** [comment]
Excellent, thank you!

**Pull request merged**
