### PR TITLE
Update French localization

### PR DESCRIPTION
**Pull request by cyril634**
- New texts updated for French
- Fix wrong translated comments (revert back to English)
- Fix minor misspellings

### CODE REVIEW

**Comment by clobber** [comment]
Hi there. Could you explain why you reverted back to English for strings in MainMenu.strings? I don't understand why. Those should be translated to French!

Gearing up for a bug fix release soon so if you have any other additions to make, this week would be a good time.

Also, in the future if you could please git [rebase & squash](http://rebaseandsqua.sh/) to keep all of these down to a single commit that'd be great.

**Comment by cyril634** [comment]
Hi,
I reverted back strings used as comments. It seems to be more useful to keep comments in original language.

**Comment by clobber** [comment]
Okay thank you. There are still merge conflicts so you will need to [rebase](http://rebaseandsqua.sh/) this in order to resolve them. Otherwise I cannot automatically merge this.

**Comment by cyril634** [comment]
It seems to be OK

**Comment by clobber** [comment]
Sorry, but you will have to **rebase** properly as now there is a useless "merge remote-tracking branch" commit. Check my link in a previous reply for more information on that.

**Pull request closed without merging**
