### PR TITLE
Localization updates and fixes

### PR DESCRIPTION
**Pull request by shysaur**
This PR:
- Fixes some string clipping, both in English and in other languages:
  - the autolayout-related changes by @J-rg from #2216 were reintroduced, and I fixed the bugs that they originally introduced (specifically, the scroll view not scrolling, and the animation glitching out)
  - the algorithm used for determining the size of the labels in the controls pref-pane was changed. This change fixes the "Bottom Right Action:" label in the Intellivision controls (it was 3 lines tall and it didn't fit), and the "Alza volume:" label in the Italian localization (it was misaligned with its button). It probably fixes some similar issues in the new Dutch localization.
- Updates German and French localizations (again, commits by @J-rg, picked from #2216)
- Changes the labels for system-specific "Pause" and "Reset" buttons to "Console Pause" and "Console Reset", to avoid mixing them up with the global "Pause" and "Reset" buttons.
- Adds some missing labels to the ControlLabels.strings files, and reorganized them a bit in the process.
- Updates the Italian localization (translated the previously-missing labels, and fixed some mistakes and inconsistencies)
- Fixes minor cosmetic issues
  - The link to the guide in the blank slate view of disc-based consoles had the wrong font (it was basically unnoticeable though)
  - The BIOS preferences panel's informational text box could scroll sideways for a couple of pixels
  - In the "Consoles" preferences panel, the separator of the last column is now invisible (commit by @J-rg from #2216)

While I basically cherry picked all the commits from #2216, I left out e9e86e25343c753c4c7b50e331a538a3fbd22c97 and eddaf2d191f378da7890ba9066f209ded79eefad because they were controversial.

I'm sorry for the high amount of commits and the bad timing, we should all be watching AGDQ right now :-)

### CODE REVIEW

**Comment by clobber** [comment]
Thanks, sorry for the delay on this. Gearing up for a bug fix release soon so if you have any other additions to make, this week would be a good time.

Could you also rebase these changes off of master again and fix the merge conflicts? We'll also want to double-check there are no weird auto layout issues with Preferences.

**Comment by shysaur** [comment]
I'll try to get the rebase done as soon as possible, this week.

**Comment by shysaur** [comment]
It should be ok now.
Note that this PR will probably conflict with #2467. I can remove any changes to those French strings files that are also being modified in #2467, if you want.

**Comment by clobber** [comment]
Thank you! Sure, regarding the French string files - go for it.

**Comment by shysaur** [comment]
Done.
Sadly, I had to remove @J-rg 's capitalization fixes; but that wasn't exactly a high-priority issue.

I also had to remove the French part of the bug fix implemented in 456bef4 (the [Library | Save States | Screenshots | Homebrew] segmented cell always appeared untranslated), but it's not difficult to apply the same fix to the new translation. That commit's diff should be self-explanatory.

(Basically the problem was that b56342d changed the segmented cell's Interface Builder ID. The string files were not changed, and thus they referred to the cell by its old ID.)

**Comment by clobber** [comment]
Thank you! Looking back, I just realized I misread your last comment about wanting to work around the possible conflicts in #2467. Would you care to revert back to before your last set of changes? Otherwise, I will just reapply the capitalization and segmented cell bug fix after this PR is merged.

#2467 is sort of unclear to me, so I don't mind if this PR generates conflicts for that one.

**Comment by shysaur** [comment]
Here you go!
Luckily I kept the old branch around...

**Pull request merged**
