### PR TITLE
Update localizations

### PR DESCRIPTION
**Pull request by J-rg**

### CODE REVIEW

**Comment by clobber** [comment]
> No description provided.

Hello there. Could you please provide a detailed description of your work (similar to #2176) and clarify if there are any outstanding issues?

I was under the impression that using Base Internationalization would not currently work with our application due to complexities/requirements for Auto Layout.

**Comment by clobber** [comment]
Some other questions raised: I see size changes here. Is that to fit larger strings in the UI? Does that affect or break anything in the interface?

You used the IT localized versions of OEMigrationWindowController.xib and OESystemPicker.xib for the Base. Why not the EN version like all the rest?

Are there any other changes you may have made to the new Base xibs since they have been renamed from the EN versions?

We appreciate your help, it's just that big changes to xibs make anyone nervous, rightfully so.

**Comment by J-rg** [comment]
> Hello there. Could you please provide a detailed description of your work (similar to #2176) and clarify if there are any outstanding issues?

I will follow up on this. There shouldn’t be any issues though.

> I was under the impression that using Base Internationalization would not currently work with our application due to complexities/requirements for Auto Layout.

Auto Layout isn’t required for using Base Internationalization. You just have to make sure the localized text fits in the interface elements of the English XIBs, since those won’t resize without Auto Layout. That’s why there are still a few XIBs around.
I thought using Base Internationalization was a good idea since 1.0.4 and current betas have issues due to outdated localized XIBs and Lion isn’t supported anymore. The worst that can happen now is clipped or untranslated text.

> Some other questions raised: I see size changes here. Is that to fit larger strings in the UI? Does that affect or break anything in the interface?

I increased the length of some TextFields to avoid clipping. I made sure everything still looks the same, don’t worry.

> You used the IT localized versions of OEMigrationWindowController.xib and OESystemPicker.xib for the Base. Why not the EN version like all the rest?

I didn’t…? Both still have English text.

> Are there any other changes you may have made to the new Base xibs since they have been renamed from the EN versions?

Besides the length adjustments and changing two ... into …, no. Xcode made a few changes, but those shouldn’t break anything.

**Comment by clobber** [comment]
Okay, thank you for the update! By the way, there was just a change to one of the xibs (MainWindow) so you will need to rebase and update your patch. But other than that, I think everything is good now. Sounds like we can pull this in.

**Comment by clobber** [comment]
Whoops, not just MainWindow but pretty much all of the xibs :P

**Comment by clobber** [comment]
Okay one last thing, if you could git [rebase & squash](http://rebaseandsqua.sh/) to remove that "Merge remote-tracking branch" commit that would be great.

**Comment by J-rg** [comment]
>No local changes to save
HEAD is now at 4ac15df Merge remote-tracking branch 'OpenEmu/master'

Doesn't seem to work and I don't really have time tinkering with Terminal to figure out what went wrong, sorry.

**Comment by clobber** [comment]
Merged, thank you!

**Comment by clobber** [comment]
By the way, the xib's MainMenu, OEPrefLibraryController, OEPrefGameplayController and OEPrefControlsController are still missing some localized .strings if you get a chance to fix those.

**Comment by J-rg** [comment]
Yeah, those have texts that would get clipped if they were inserted in the English XIB.
I’ll update their Base to Auto Layout next week and then convert those.

I didn’t update the MainMenu to preserve the translated „Special thanks to…“ texts, since they can’t be translated using Base Localization apparently.
I’ll move them to Localizable.strings for now, they probably have to be inserted by code anyway.

**Comment by shysaur** [comment]
> [...] they probably have to be inserted by code anyway.

I've just finished writing a PR that does just that; I'm going to submit it right now.

**Pull request merged**
