### PR TITLE
Various changes

### PR DESCRIPTION
**Pull request by J-rg**
Sorry for the vague title, here’s the changelog:

- Remove some titles and placeholders from XIB files, they serve no function and clutter up localization files
- Remove obsolete strings from translation files
- Rename Path to Name in the fix import issues view since that’s what is displayed in the column
- Remove system frameworks from project, they are linked automatically in Xcode 5 and newer
- Fix playing indicator in list view: https://cl.ly/6140157c7820
- Remove unused image assets from project
- Slightly change the selection color in list view. The former color turned purple if Night Shift / f.lux is enabled: https://cl.ly/b419ba5ffca6
- Add ellipsis after „Edit Game Controls“ according to Apple’s HIG because it „requires additional input from the user“
- Update German localization
- The tooltip for the play/pause button in the HUD now reads „Resume Gameplay“ if gameplay is currently paused
- Add Satellaview (.bs) and Sufami Turbo (.st) file extensions to the SNES system plugin. No-Intro put them into separate dats a while ago and assigned them their distinct file extensions.

### CODE REVIEW

**Comment by clobber** [comment]
Thanks. We're trying to get a release out this weekend or early next week, since 10.14 is coming out and 2.0.6.1 crashes on it, so we will try to review this in time. By the way, we have a Discord server set up if you want to follow development more closely: https://discord.gg/UEwsRv

**Comment by robotoad** [comment]
My only concern is losing the documentation provided by those placeholder titles.

**Comment by J-rg** [comment]
I added back the titles that show up in the preview in interface builder, e.g. the path to the library folder. I hope that’s what you meant.

**Comment by clobber** [comment]
@J-rg can you drop by our Discord? Easier to discuss that way.

**Comment by robotoad** [comment]
@J-rg Thanks. In the future, I think we'd like to start using the Localizer Hint field to flag non-localized elements in IB, perhaps with "DNT" (Do Not Translate) or some other marker.

**Pull request merged**
